@echo off
echo Starting OrbVeil Backend...
start cmd /k "python -m uvicorn src.orbveil.api.main:app --reload --host 0.0.0.0 --port 8000"

echo Starting OrbVeil Frontend...
start cmd /k "cd dashboard && npm run dev"
